### PR TITLE
Fixed Paths to files appdaemon 

### PR DESCRIPTION
**Pull request by ikifar2012**

### CODE REVIEW

**Comment by Landrash** [comment]
These paths aren't wrong?
Is this a proposed change and if so what are the reason?

**Comment by ikifar2012** [comment]
Why not put them in the home assistant install directory or better yet have the script create samba share

**Comment by Landrash** [comment]
@ikifar2012 Appdaemon doesn't require HA to run on the Raspberry pi. Didn't see the need to try and put it alll in the same directory since it's not neeeded.

@acockburn Would you mind giving you opinion?

**Comment by acockburn** [comment]
@landrash - I agree. As the user is free to place AppDaemon configuration files anywhere and HASSBIAN is not concerned with the install, there is no 100% right answer here, and no compelling reason to change what is already here. If HASSBIAN did install AD it would make sense to keep it consistent but that is not the case.

Ultimately AD will integrate with HASS and there will be officially correct directories for all of its content and the startup will be handled via HASS so these will not even be needed at some point in the future.

**Comment by ikifar2012** [comment]
how about if it created a samba share?

**Comment by Landrash** [comment]
@ikifar2012 If you would like to create a samba share fell free to submit a script that does that. Should be fairly simple to modify the current samba script to accomplish that :) That would be in a separate Pr so closing this one. 

@acockburn Thanks for your quick response :cake:

**Pull request closed without merging**
