### PR TITLE
Add status of installed suites, plus interrogation of state with JSON results.

### PR DESCRIPTION
**Pull request by kxtcd950**
Partially complete code: I've tested most of the code, but would appreciate feedback and additional testing based on unexpected (to me) usage of the script.  My apologies in advance if it's incomplete.

Adds a persistent state for each suite installed.  This state can be fetched by using the new ```hassbian-config``` ```state``` command.  This new command will return the states of all installed and available suites in JSON format.
The states of the suites are:
* installed - the suite is installed
* failed - an install was attempted, but it failed
* uninstalled - the suite is available to install

The JSON returned is built in parts through text concatenation (no native JSON libraries in bash scripting), all emitted JSON to date has passed the syntactic parsing done by http://json.parser.online.fr/ which I found using a google search.  The JSON is therefore assumed to be correctly formed.

installer_*.sh scripts have changed so that instead of calling exit, the installer function returns error/success and hassbian-config checks that returned value and adjusts the packages state as appropriate.

### CODE REVIEW

**Comment by balloob** [comment]
As far as I understand it, the code looks good 👍

**Comment by balloob** [comment]
From what I can read, it looks like this, is this correct?

```json
{
  "suites": [
    {
      "openzwave": [
        {
          "state": "installed"
        },
        {
          "description": "This is the description"
        }
      ]
    }
  ]
}
```

**Comment by balloob** [comment]
I would prefer a more compact version, ie:

```json
{
  "suites": {
    "openzwave": {
      "state": "installed",
      "description": "This is the description"
    }
  }
}
```

**Comment by kxtcd950** [comment]
THe JSON is actually returned as a one line string of text thus:
```{ "suites" : [ { "openzwave" : [ { "state": "Uninstalled" }, { "description": "Installs the Open Z-wave package for setting up your zwave network" } ] } ] }```

It's the online parsers that "pretty-print" it into the expanded version.  I can add newlines and other whitespace as needed, but my initial concern was making the JSON syntactically correct; it never occurred to me to make it human friendly ;)

I've now got it returning something a lot more like what you wanted:
```JSON
{
    "suites":{
        "libcec":{
            "state":"Uninstalled",
            "description":"Installs the libcec package for controlling CEC devices from this Pi"
        },
        "mosquitto":{
            "state":"failed",
            "description":"Installs the Mosquitto package for setting up a local MQTT server"
        },
        "openzwave":{
            "state":"Uninstalled",
            "description":"Installs the Open Z-wave package for setting up your zwave network"
        },
        "samba":{
            "state":"installing",
            "description":"Installs the samba package for sharing the hassbian configuration files over the Pi's network."
        }
    }
}
```
although I'm still returning it as one line of text - no embedded carriage returns; the above is the output of a pretty printer :)
I'll just check there's nothing broken and update the pull request once you confirm that's more useful to you.

The basic problem - for which I apologise - is that I come from a C background (I write C for embedded systems professionally) and so JSON is completely alien to me - when I think of a load of objects in sequence, my brain is trained to think of an array.  Hence all the arrays in the returned JSON.

**Comment by balloob** [comment]
Newlines and spaces in JSON are optional so it's all good. The new format is a lot nicer 👍  thanks

**Pull request merged**
