### PR TITLE
Adds hassbian manager script

### PR DESCRIPTION
**Pull request by ludeeus**
## Description:

This adds a "Hassbian manager" web tool to manage hassbian-config suites.
[Image from Gyazo](https://gyazo.com/5ae526559e7a19ceef97621b741647de)

## Checklist (Required):
  - [x] The code change is tested and works locally.
  - [x] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [x] Script has validation check of the job.
  - [x] Created/Updated documentation at `/docs`

### CODE REVIEW

**Review by Landrash — DISMISSED** [review]
Looks good to me and ok to merge when you consider it finished.

**Comment by ludeeus** [comment]
Since this and #238 have the same base, I'll hold off to see if I can include auth here to

**Comment by ghost** [comment]
When it will be implemented ?

**Comment by ludeeus** [comment]
First it needs to be done, then pass a second review, then be merged, then wait for a new version containing this.

**Comment by ludeeus** [comment]
Should be good now, @Landrash want to have another look? :)

**Review by Landrash — APPROVED** [review]

**Pull request merged**
