### PR TITLE
Using Letsencrypt Certs with Shellinabox

### PR DESCRIPTION
**Pull request by juan11perez**
### Description: Using letsencrypt certificates with Shellinabox to create an error free https:// instance.
These are the steps i took to obtain a functioning sample: 

1)Enabled ssl by confirming sudo nano /etc/default/shellinabox with: SHELLINABOX_ARGS="--no-beep"

2)Created a bash script to automate concatenating and symlinking the fullchain.pem and privekey.pem files in /etc/letsencrypt/live/mydomain.duckdns.org/

sudo nano /usr/local/bin/shellinabox_certificate
#!/bin/bash                                                                                                                                            
sudo unlink /var/lib/shellinabox/certificate-mydns.duckdns.org.pem                                                                               
sudo rm /home/hass/Downloads/certificate-mydns.duckdns.org.pem                                                                                   
cat /etc/letsencrypt/live/mydns.duckdns.org/privkey.pem /etc/letsencrypt/live/mydns.duckdns.org/fullchain.pem > /home/hass/Downloads/certificate-mydns.duckdns.org.pem                                                                                                                      
sudo chmod 755 /home/hass/Downloads/certificate-mydns.duckdns.org.pem                                                                            
sudo ln -sf /home/hass/Downloads/certificate-mydns.duckdns.org.pem /var/lib/shellinabox/certificate-mydns.duckdns.org.pem                  
sudo invoke-rc.d shellinabox restart

3) Created an automation to update the symlink when letsencrypt auto-renews

- id: shellinabox_certificate_update
  alias: Shellinabox certificate update
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    above: 89
    for: 23:59:00
  action:
    service: shell_command.shellinabox_certificate

4) added the following to sudo visudo
homeassistant ALL=(ALL) NOPASSWD:SETENV: /usr/local/bin/shellinabox_certificate

5) added to panel frame

shellinabox

### CODE REVIEW

**Comment by Landrash** [comment]
There's nothing added in this PR?
Your just trying to merge our dev branch into master.

**Comment by juan11perez** [comment]
apologies, I dont know how to do this. I wanted to share the subject. I'll just close it.

**Comment by Landrash** [comment]
@ludeeus Can you rework the information from this PR into the shellinabox script?
We could check if letsencrypt/duck dns is installed and if so install this?

**Comment by ludeeus** [comment]
@Landrash I can try :)

**Pull request closed without merging**
