### PR TITLE
Hassbian: Added automated update options.

### PR DESCRIPTION
**Pull request by swetoast**
**Description:**

An update that enables automated updates to hassbian.sh with the option for pushbullet and pushover notifications also cleans up old configurations and old packages

**Related issue (if applicable):** Fixes #<hassbian-scripts issue number goes here>

## Checklist (Required):
  - [X] The code change is tested and works locally.
  - [X] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [ ] Script has validation check of the job.
  - [ ] Created/Updated documentation at `/docs`

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @swetoast, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#173).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by Landrash — COMMENTED** [review]
I like the concept but some things concern me

Default for updates should most likely be weekly at most.

Debian has an offical way of handling automated updates [cron-apt](https://debian-administration.org/article/162/A_short_introduction_to_cron-apt) and that should most likely be be best way of handling the automated part.

Notification handlers should most likely be moved out of this suite into a separate handler.

**Comment by swetoast** [comment]
we can change to cron.weekly and yes cron-apt is standard and moving notification to a separate handler is ok but feel free to modify to best suite hassbian or if you want me to do it just ping :)

**Review by ludeeus — CHANGES_REQUESTED** [review]
I agree with @Landrash move this to weekly.

`cron-apt` is new for me, so that part I will leave to you to.

For the notify part:
- Should not be a part of a single suite (package)
 - each proviver should have its own install script with documentation.
 - The notify logic should be inside `hassbian-config` and preferably invoked by
`--notify-pushover` and `--notify-pushbullet`

**Review by tomytah — APPROVED** [review]

**Comment by Landrash** [comment]
@tomytah This shouldn't be approved in it's current form.

**Comment by Landrash** [comment]
Closing to be replaced by native automated updates by Apt package manager in Debian/Ubuntu.

**Pull request closed without merging**
