### PR TITLE
Change header from "Monitor" to "Pi-hole"

### PR DESCRIPTION
**Pull request by Sirs0ri**
## Description:

No Code-changes, no related issue, etc. This just changes the header of the script's documentation, fixing what looks like a copy/paste-error to me.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Sirs0ri, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#213).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by ludeeus — APPROVED** [review]
Thanks :)

**Comment by Sirs0ri** [comment]
You're absolutely welcome, I'm glad to help!

**Comment by Landrash** [comment]
Defiantly a copy paste error by me. I copied the file for monitor when I created the pi-hole script 😑

**Pull request merged**
