### PR TITLE
Documentation cleanup

### PR DESCRIPTION
**Pull request by ludeeus**
## Description:
Cleans up all documentation files.

## Checklist (Required):
  - [ ] The code change is tested and works locally.
  - [X] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [ ] Script has validation check of the job.
  - [X] Created/Updated documentation at `/docs`

### CODE REVIEW

**Comment by ludeeus** [comment]
Sorry about the volume, I didn't realize it would be that big :/

**Comment by Landrash** [comment]
Looks awesome! 

Wondering about the removal of the $ infront off commands. Reason for it to exist is to confirm with how guides are usually written for Linux. 

What's your reason for their removal?

**Comment by ludeeus** [comment]
My markdown linter complained about it,
I can grab the message when I get home ;)

**Comment by ludeeus** [comment]
@Landrash This is the complain it had about it:
<https://github.com/updownpress/markdown-lint/blob/master/rules/014-commands-show-output.md>

**Comment by Landrash** [comment]
I agree with the Linter. Ok to merge! 😁

**Review by Landrash — APPROVED** [review]

**Pull request merged**
