### PR TITLE
Python: Limit python version to 3.6.6.

### PR DESCRIPTION
**Pull request by ludeeus**
## Description:
Limits the version that is installed with the python upgrade script.

## Checklist (Required):
  - [X] The code change is tested and works locally.
  - [X] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [X] Script has validation check of the job.
  - [X] Created/Updated documentation at `/docs`

### CODE REVIEW

**Comment by Landrash** [comment]
Is there any reference information about the problems at hand that can be included in the documentation?

**Comment by ludeeus** [comment]
I can get some, HA did not start at all for me (and others on Discord) when running Python 3.7.0
It said something about missing attributes for setup.

I will install it agein and se if I can make sense of it :)

**Comment by Landrash** [comment]
That's a good enough reason for me.
Add a timestamp of when we added in this check/limit and add removal of this limitation to the todo :)

**Comment by ludeeus** [comment]
I must have done something terrible with my testing, not sure how, it was a fresh install of Hassbian.
Or something has changed in 3.7.0 / homeassistant
This does not happen for me anymore.....
Closing this PR

**Pull request closed without merging**
