### PR TITLE
Add some error handling to these scripts

### PR DESCRIPTION
**Pull request by tcrichton**
- Exit the script upon error
- Print commands if DEBUG environment variable is set

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @tcrichton, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#28).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by Landrash** [comment]
@tcrichton Would you mind having a look if your suggested changes can be integrated into the `dev` branch?

**Comment by tcrichton** [comment]
No problem, I'll take a look when I find some time.

Tristan.

**Comment by Landrash** [comment]
Closing since base script is getting reworked.
Thanks for the PR and the idea of this will most likely be reworked :)

**Pull request closed without merging**
