### PR TITLE
Added log functionality and easy hastebin sharing.

### PR DESCRIPTION
**Pull request by ludeeus**
Added writing to an logfile for every install/upgrade, this "function" will overwrite the file so only the latest one is available.

Added "log"  as an cmd option.
This will produce an hastebin link to easy share the log of the last install/upgrade.

### CODE REVIEW

**Comment by ludeeus** [comment]
If this is included, the scripts (that have verification check) can be edited to post an hastebin link when script fails.

**Comment by Landrash** [comment]
It might be wise to have a log only do a `more` on the file a create a `share-log` file to hastebin. Looks good else :)

**Comment by ludeeus** [comment]
Maybe, I did not know about `more` until now :P

**Review by Landrash — APPROVED** [review]
Looks good and tagged for 0.7.
A few conflicts between your pr's. Mind resolving them?

**Comment by ludeeus** [comment]
This should also be ok bow :)

**Review by Landrash — APPROVED** [review]

**Pull request merged**
