### PR TITLE
create homeassistant update script

### PR DESCRIPTION
**Pull request by JudgeDreddKLC**
this can probably be merged into the install script with a switch.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kentcalero, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#15).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by Landrash** [comment]
With the changes that have been done to the base image this won't work currently.
I'm going to try and work in support for scripts like these also soo I'll leave this pull request open.

**Comment by JudgeDreddKLC** [comment]
Sounds good, bash scripting is not my forte but this can be easily be part of the install script, default can be install, or upgrade if already installed. We can have a reinstall switch that will remove and reinstall and an uninstall switch. I'll be more than happy to work ok this once you have an updated install script.

**Comment by JohanLeirnes** [comment]
Will this work now?

**Comment by Landrash** [comment]
@bhaap It hasn't been rewritten as of yet and I'm in the middle of moving and renovating a house so my free time is a tad limited currently.

**Comment by JudgeDreddKLC** [comment]
@bhaap Assume it does not work, I have not touched it and the install process has been changed heavily since then. I need to make time to run through all the installations again and take new notes.

**Pull request closed without merging**
